Added 'timeout' option for  baseclient
aatikturk/obsws-python pull request #27
Opened 2023-05-29 10:54 UTC by aatikturk

Hi Onyx,
This PR is introducing following changes to fix #25 :

- Added timeout parameter for the baseclient.
```python3
 def __init__(self, **kwargs):
        defaultkwargs = {"host": "localhost", "port": 4455, "password": "", "subs": 0, "timeout":3}
```
```python3
        self.ws = websocket.WebSocket()
        self.ws.connect(f"ws://{self.host}:{self.port}", timeout=self.timeout)
        self.server_hello = json.loads(self.ws.recv())
``` 
- in the ```req```  method while sending the request exception handling implemented.
```python3
        try:
            self.ws.send(json.dumps(payload))
        except TimeoutError:
            raise OBSSDKError("Timeout while trying to send the request")
```

- [x]  tests passed
- [x] readme updated
- [x] version bumped

Thanks for your time!

2023-06-03 12:07 UTC, onyx-and-iris requested changes

2023-06-13 22:19 UTC, aatikturk commented on README.md
Thanks for pointing that out. Removed timeout example from `config.toml`  example.

2023-06-15 14:22 UTC, onyx-and-iris commented
Hi Adem. Thanks for your updates. I have a some further changes I'd like to run by you if you can write to me on discord when you get a bit of spare time.

For example, we may consider raising a more descriptive error class for TimeoutErrors. It would be worth logging these exceptions as well, while we're at it we may log some other possible exceptions that can occur. Example ConnectionRefusedError on initial connection.

We should also update the `__repr__` methods with timeout parameters.

Just let me know when you have a bit of time to discuss. Thanks.

2023-06-19 17:13 UTC, onyx-and-iris approved these changes

2023-06-19 17:23 UTC, onyx-and-iris commented
Thanks for the chat earlier. I've pushed a few of the changes we discussed.

A new error class `OBSSDKTimeoutError` will be raised if a timeout occurs in baseclient.req() or eventclient.trigger().

Some error/exception logging.

Add new error class to README.

I've also shifted the version bump to minor.

2023-06-19 17:25 UTC, merged